### ISSUE TITLE
Put on crates.io

### ISSUE THREAD

**Issue by bfrog** [danburkert/memmap-rs#1]
would be nice to see this on crates.io

**Comment by danburkert** [comment]
I plan to, but right now it's blocked on retep998/winapi-rs publishing an updated crate (crates.io does not allow you to publish with non-crates.io dependencies).

**Comment by retep998** [comment]
You should no longer be blocked on that.

**Comment by BurntSushi** [comment]
@danburkert ping. Is there anything I can do to help get this on crates.io?

**Comment by danburkert** [comment]
Hi all, sorry for the radio silence on this.  I'm of the opinion that this project should be combined with [rbranson/rust-mmap ](https://github.com/rbranson/rust-mmap), and be pushed to crates.io as an update to that project.  I'm attempting to reach out to the owner of that project via rbranson/rust-mmap#5, but there's no word back yet.  If there's enough demand I may just go ahead and push under a different name.  I'd also like to get a solution to #4 before pushing since that is almost certainly going to change the API.

**Comment by xrl** [comment]
@danburkert I've emailed @rbranson about this issue and haven't heard back. I think it's time to publish under another name? Is `mmap-sys` available?

This is holding me up from publishing my `mmap`-backed database lib.

**Comment by retep998** [comment]
Perhaps `memmap` or `memorymap`?

**Comment by jan-hudec** [comment]
I support @retep998's suggestions. https://crates.io/ does not have either.

**Comment by xrl** [comment]
The `-sys` suffix is the working convention for "system bindings". `mmap-sys` is open. You can view `-sys` packages here: https://crates.io/search?q=-sys . This library would follow that convention.

**Comment by retep998** [comment]
But this crate does not provide raw bindings to a specific system library. Rather it provides a high level wrapper around system stuff provided by _other_ crates.

**Comment by xrl** [comment]
That's fair. I vote `memorymap`.

**Comment by danburkert** [comment]
The project has been renamed to `memmap`, and pushed to [crates.io](https://crates.io/crates/memmap).  Thanks all!
