### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by alexreg** [danburkert/memmap-rs#18]
Thanks for your work on this library; very useful indeed! I just had a few things I was wondering about:
- Are `MmapView`/`MmapViewSync` simply for allowing different owners of different parts of the mmap? (I presume this doesn't cause any fragmentation of the underlying map.)
- In what sense is `MmapViewSync` more 'thread-safe' than `MmapView`? Accessing/modifying data seems to be equally un-thread-safe from both, so what's the difference?
- For the `clone` method, you state _The underlying memory map is shared, and thus the caller must ensure that the memory underlying the view is not illegally aliased._ – what sort of aliases are you referring to here?

**Comment by alexreg** [comment]
Relating to the 3rd point, I also see that for the `MmapView(Sync)` type, it's stated *A mmap view is not cloneable.* – yet the `clone` method exists with the above warning – now I'm just confused!

**Comment by BurntSushi** [comment]
It looks like the `clone` methods were [added recently](https://github.com/danburkert/memmap-rs/commit/ac68f9348b16d32ecd1c237e0bd2a4764c7efd30). My guess is that the docs just haven't been updated yet.

> Are MmapView/MmapViewSync simply for allowing different owners of different parts of the mmap? (I presume this doesn't cause any fragmentation of the underlying map.)

That's mostly how I see it, yes. I'm not sure what you mean by fragmentation of the underlying map, but multiple `MmapView` values created by the same `Mmap` value will share the same underlying memory map.

> In what sense is MmapViewSync more 'thread-safe' than MmapView? Accessing/modifying data seems to be equally un-thread-safe from both, so what's the difference?

They are not equally unsafe. The difference is that `MmapView` uses a `std::rc::Rc` while a `MmapViewSync` uses a `std::sync::Arc`. This means that an `MmapView` cannot be used simultaneously across multiple threads, nor can its ownership be transferred from one thread to another (because `Rc` is not `Send` nor `Sync`).

> For the clone method, you state The underlying memory map is shared, and thus the caller must ensure that the memory underlying the view is not illegally aliased. – what sort of aliases are you referring to here?

Memory maps can be shared and mutated by multiple processes with reckless abandon. If you have a `&[u8]`, then Rust says that it is not mutably aliased anywhere else, and that safe code should not mutate it. The `memmap` crate can't provide this guarantee because we are at the mercy of the underlying operating system. Therefore, functions that access the memory mapped data are unsafe.

I am somewhat skeptical of how safety is handled in this crate, but don't necessarily have any better ideas. Namely, it seems like the unsafety of shared memory maps are impossible to encapsulate, so it's hard to see how *any* interaction with the data could be declared as safe. (Which I find troubling.)

**Comment by alexreg** [comment]
> It looks like the clone methods were added recently <https://github.com/danburkert/memmap-rs/commit/ac68f9348b16d32ecd1c237e0bd2a4764c7efd30>. My guess is that the docs just haven't been updated yet.
> Are MmapView/MmapViewSync simply for allowing different owners of different parts of the mmap? (I presume this doesn't cause any fragmentation of the underlying map.)
> 
> That's mostly how I see it, yes. I'm not sure what you mean by fragmentation of the underlying map, but multiple MmapView values created by the same Mmap value will share the same underlying memory map.
> 
Fair enough. It would certainly be useful if they all implemented some Mmap trait though, for their common methods.
> In what sense is MmapViewSync more 'thread-safe' than MmapView? Accessing/modifying data seems to be equally un-thread-safe from both, so what's the difference?
> 
> They are not equally unsafe. The difference is that MmapView uses a std::rc::Rc while a MmapViewSync uses a std::sync::Arc. This means that an MmapView cannot be used simultaneously across multiple threads, nor can its ownership be transferred from one thread to another (because Rc is not Send nor Sync).
> 
Okay, so MmapViewSync just ensures that references to the mmap across threads are all valid? Are any of the read/write operations guaranteed to be atomic? (I suppose not.)
> For the clone method, you state The underlying memory map is shared, and thus the caller must ensure that the memory underlying the view is not illegally aliased. – what sort of aliases are you referring to here?
> 
> Memory maps can be shared and mutated by multiple processes with reckless abandon. If you have a &[u8], then Rust says that it is not mutably aliased anywhere else, and that safe code should not mutate it. The memmap crate can't provide this guarantee because we are at the mercy of the underlying operating system. Therefore, functions that access the memory mapped data are unsafe.
> 
Fair enough, but won’t Rust enforce aliasing anyway, within a process? I don’t see why `clone` introduces any special concerns still.
> I am somewhat skeptical of how safety is handled in this crate, but don't necessarily have any better ideas. Namely, it seems like the unsafety of shared memory maps are impossible to encapsulate, so it's hard to see how any interaction with the data could be declared as safe. (Which I find troubling.)
>

**Comment by BurntSushi** [comment]
> Fair enough. It would certainly be useful if they all implemented some Mmap trait though, for their common methods.

/shrug

> Okay, so MmapViewSync just ensures that references to the mmap across threads are all valid? Are any of the read/write operations guaranteed to be atomic? (I suppose not.)

1. Yes. 2. No. This is a low level API. Building in additional atomicity guarantees would be a mistake.

> Fair enough, but won’t Rust enforce aliasing anyway, within a process? I don’t see why `clone` introduces any special concerns still.

I'm not sure why `clone` is unsafe either. All it's doing is bumping the reference count. @danburkert?

**Comment by danburkert** [comment]
Hi all, sorry for the delay, still getting into the swing of things after the Holiday break.  @BurntSushi is correct about everything he answered.

I added the clone method because I needed a way to write to a mmap from one thread, and msync it from another.  You are right that I need to update the documentation.  As to whether clone should be safe or unsafe, I was probably a little too conservative in labeling it unsafe.  Cloning a view has to be done with extreme care, but cloning by itself can not cause unsafety.  It can, however, make it easier to use the slicing methods unsafely.  It does seem a little disingenuous to `impl Clone` though, since its a shallow clone instead of the normal Rust deep clone.  Perhaps clone should be called something else.

A couple of thoughts on the view types:

1) The view types are meant to make it easier to use mmap'd memory safely in Rust applications.
2) The view types use only the public API of the `Mmap` type, so they could be implemented outside the `memmap` crate if so desired, or if tweaks are needed.
3) If the user ensures that no one else has mmap'd the same memory (file) at the same time, and that the view is never cloned, then using the view should always be safe (i.e. the unsafe slice methods may always be called safely).
4) all bets are off if either of the preconditions in #3 are violated.

**Comment by BurntSushi** [comment]
> since its a shallow clone instead of the normal Rust deep clone. Perhaps clone should be called something else.

I think it's probably fine. I see the mmap view types as analogous to slices, and [cloning a slice is shallow as well.](http://is.gd/U8PJmP)

**Comment by danburkert** [comment]
The difference is slices are restricted by lifetimes but the mmap views are not, so it's a lot easier to do bad things.

**Comment by alexreg** [comment]
@BurntSushi Cloning a slice seems to return a pointer to the same memory location, which is very odd indeed! So that's not even a shallow clone. Perhaps it's an optimisation kicking in, since the clone isn't modified?

**Comment by BurntSushi** [comment]
@alexreg It's not odd at all actually. :-) There is a `impl<'a, T> Clone for &'a T where T: ?Sized` in `std`. In fact, any `&T` is also `Copy` as well!

**Comment by alexreg** [comment]
@danburkert Thanks for your reply. That clarifies a few things.

Regarding `clone`, it seems fair to say the method itself is indeed safe and shouldn't be marked as `unsafe` itself. It need not be a deep-clone to implement `Clone`, since `Rc<T>` just does what you do here, and increments the reference count, without doing a deep clone, as do ordinary references. What might make more sense is to remove the `Clone` implementation though, and force users to wrap the `Mmap` in `Mutex` or `RwLock` in order to get safe (intra-process) usage from multiple threads. Inter-process mmaps of the same underlying file would of course suffer from memory aliasing issues, and that should be left up to the user in any case.

Also note that there are no memory aliasing issues with `clone`, since it is only cloning the reference to the underlying memory, and it's not like there are two memory-mapped regions to the same file...

Finally, what do you think about either having `Mmap` and `MmapView(Sync)` implement a common trait for their common methods, or alternatively just having one `Mmap` type, which is perhaps an enum with options `MmapRoot` and `MmapView` or something similar. Also, doesn't an `MmapView` currently have a reference to the system handle for the mmap, or such – so it would indeed be restricted by lifetimes?

**Comment by alexreg** [comment]
@BurntSushi Yes, I misunderstood. You're actually just cloning (copying) the slice reference there. A slice *itself* does not in fact implement `Clone`.

**Comment by dtolnay** [comment]
Is this issue tracking any changes we need to make to documentation, or was everything settled here?

**Comment by alexreg** [comment]
A clarification in documentation would be nice, and probably wouldn't need a lot of effort, but I'll leave that up to @danburkert to decide. :-)

**Comment by danburkert** [comment]
The `MmapView` type has been removed, and we have some other issues tracking documentation so I'm going to go ahead and close.
