### ISSUE TITLE
Implement Read + Seek for Views?

### ISSUE THREAD

**Issue by nagisa** [danburkert/memmap-rs#23]
Seems to me that `View` could implement these pretty effortlessly, though it might collide somewhat with `split_at`. I assume Seek would ignore `splits` and work in terms of underlying map, though.

**Comment by danburkert** [comment]
This would require having the `View` type keep track of its current position internally, right?  Could you instead get the same effect by wrapping a [`Cursor`](https://doc.rust-lang.org/nightly/std/io/struct.Cursor.html) around the view?

**Comment by nagisa** [comment]
> This would require having the View type keep track of its current position internally, right?

I feel like both of these could be implemented by adjusting the `offset` and `len` that’re already inside the view.

Namely:

* `Read::read` would memcpy appropriate amount of bytes into provided slice and increase `offset` (as well as decrease `len`) by the amount of bytes read;
* `Seek::seek(SeekFrom::Start(x))` would set the `offset` to `x` and `len` to the length of underlying Mmap - x;
* `Seek::seek(SeekFrom::End(x))` would set the offset to length of underlying Mmap - x and len to `x`
* `Seek::seek(SeekFrom::Current(x))` similarly.

However, I see how they could interfere with the splitting feature Views provide. Either way, if you feel I’m making no sense, feel free to close.

**Comment by danburkert** [comment]
Ah, I didn't catch your meaning at first.  I like the idea, except I think the seek functionality should be relative to the view itself, not the underlying mmap.  One of the nice guarantees of `MmapView` is that you can use it to partition off different areas of a single `mmap`, so leaking data from outside the range is bad.

`Cursor<MmapView>` is probably not possible because it requires an `AsRef<[u8]>` implementation for the view, which is not possible because of unsafety.  If that's something you want, you could copy the source for the view into your own project and update accordingly (but obviously be careful to understand the potential unsafety).  The `MmapView` implementation uses only the public APIs exposed by `Mmap`.  I've been considering removing it altogether, since people frequently have slightly different needs for the view (such as this), which require changing it slightly in a way that's not necessarily feasible for a published library crate.  It is nice to have it as a model implementation, though.

**Comment by dtolnay** [comment]
What are the things we need to follow up on here? Have we decided to remove MmapView?

**Comment by danburkert** [comment]
Yep, the view types have been removed on master.  I'm going to close this, given that it's no longer applicable.
