### ISSUE TITLE
Docs should say why file-backed maps are unsafe

### ISSUE THREAD

**Issue by federicomenaquintero** [danburkert/memmap-rs#70]
In contrast to the functions to create anonymous maps, all the file-backed ones are marked `unsafe`.  However, the docs don't say why this is.

What I can glean from #25 is that while memmap would have one believe that one gets an immutable `&[u8]` out of a map, in reality the file can change underneath and one may need to take extra measures like file locking and whatnot.

Is this accurate?  If so, I can submit a PR to update the docs to that effect.

**Comment by BurntSushi** [comment]
The actual story here is quite complex. There was a recent thread on urlo, and as far as I can tell, there is no obvious consensus on how to document this. https://users.rust-lang.org/t/how-unsafe-is-mmap/19635

It would be good to point out this issue in the documentation however, but I don't think we can write anything authoritatively yet.

**Comment by federicomenaquintero** [comment]
Thanks, @BurntSushi :smiley:

**Comment by faulesocke** [comment]
There are two reasons:

1. Because you can get multiple maps to the same region in the same file, both mutable and immutable at the same time.
2. The memory (even the immutable one) is file-backed. If the file changes (even if it changes from outside the process), the memory contents will change with it. Therefore immutable memory may change randomly which is highly unsafe.

**Comment by danburkert** [comment]
#66 landed with improved descriptions of why unsafe is necessary.  If you still feel the documentation is lacking please feel free to open a new issue/PR with a specific proposal.  Thanks!
